# Generated by Django 3.1.6 on 2022-08-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_by', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='blog')),
            ],
        ),
    ]
