# Generated by Django 3.1.6 on 2022-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=255)),
                ('short_url_id', models.CharField(max_length=255)),
            ],
        ),
    ]
